import type { InsertAccount } from "@shared/schema";

export interface DefaultAccountTemplate {
  code: string;
  nameEn: string;
  nameAr: string;
  description: string;
  type: "asset" | "liability" | "equity" | "income" | "expense";
  subType: string | null;
  isVatAccount: boolean;
  vatType: "input" | "output" | "zero_rated" | "exempt" | null;
  isSystemAccount: boolean;
}

export const defaultChartOfAccounts: DefaultAccountTemplate[] = [
  // ===========================
  // ASSETS - Current Assets (1000-1099)
  // ===========================
  {
    code: "1010",
    nameEn: "Cash on Hand",
    nameAr: "النقد في الصندوق",
    description: "Physical cash held at business premises",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1020",
    nameEn: "Bank Accounts",
    nameAr: "الحسابات البنكية",
    description: "Funds held in business bank accounts",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1030",
    nameEn: "Petty Cash",
    nameAr: "النثرية",
    description: "Small cash fund for minor expenses",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1040",
    nameEn: "Accounts Receivable",
    nameAr: "الذمم المدينة",
    description: "Amounts owed by customers for goods/services",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1050",
    nameEn: "VAT Receivable (Input VAT)",
    nameAr: "ضريبة القيمة المضافة المستردة",
    description: "VAT paid on purchases, recoverable from FTA",
    type: "asset",
    subType: "current_asset",
    isVatAccount: true,
    vatType: "input",
    isSystemAccount: true,
  },
  {
    code: "1060",
    nameEn: "Prepaid Expenses",
    nameAr: "المصروفات المدفوعة مقدماً",
    description: "Expenses paid in advance (rent, insurance, etc.)",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1070",
    nameEn: "Inventory",
    nameAr: "المخزون",
    description: "Goods held for sale or production",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // ASSETS - Fixed Assets (1200-1299)
  // ===========================
  {
    code: "1210",
    nameEn: "Office Equipment",
    nameAr: "معدات المكتب",
    description: "Office machines, printers, and equipment",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1220",
    nameEn: "Furniture & Fixtures",
    nameAr: "الأثاث والتركيبات",
    description: "Office furniture, desks, chairs, shelving",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1230",
    nameEn: "Computers & Software",
    nameAr: "الحواسيب والبرمجيات",
    description: "Computer hardware and capitalized software",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1240",
    nameEn: "Accumulated Depreciation",
    nameAr: "الاستهلاك المتراكم",
    description: "Total depreciation of fixed assets",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },

  // ===========================
  // LIABILITIES - Current Liabilities (2000-2099)
  // ===========================
  {
    code: "2010",
    nameEn: "Accounts Payable",
    nameAr: "الذمم الدائنة",
    description: "Amounts owed to suppliers and vendors",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2020",
    nameEn: "VAT Payable (Output VAT)",
    nameAr: "ضريبة القيمة المضافة المستحقة",
    description: "VAT collected on sales, payable to FTA",
    type: "liability",
    subType: "current_liability",
    isVatAccount: true,
    vatType: "output",
    isSystemAccount: true,
  },
  {
    code: "2025",
    nameEn: "FTA VAT Control Account",
    nameAr: "حساب مراقبة ضريبة القيمة المضافة - الهيئة الاتحادية للضرائب",
    description: "Net VAT payable/receivable to Federal Tax Authority",
    type: "liability",
    subType: "current_liability",
    isVatAccount: true,
    vatType: "output",
    isSystemAccount: true,
  },
  {
    code: "2030",
    nameEn: "Salaries Payable",
    nameAr: "الرواتب المستحقة",
    description: "Unpaid employee wages and salaries",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2040",
    nameEn: "Accrued Expenses",
    nameAr: "المصروفات المستحقة",
    description: "Expenses incurred but not yet paid",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2050",
    nameEn: "Deferred Revenue",
    nameAr: "الإيرادات المؤجلة",
    description: "Payments received before goods/services delivered",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // LIABILITIES - Long-term Liabilities (2200-2299)
  // ===========================
  {
    code: "2210",
    nameEn: "Loan Payable",
    nameAr: "القروض المستحقة",
    description: "Long-term bank loans and financing",
    type: "liability",
    subType: "long_term_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2220",
    nameEn: "Lease Liabilities",
    nameAr: "التزامات الإيجار",
    description: "Operating and finance lease obligations",
    type: "liability",
    subType: "long_term_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // EQUITY (3000-3099)
  // ===========================
  {
    code: "3010",
    nameEn: "Owner's Capital / Share Capital",
    nameAr: "رأس مال المالك / رأس المال",
    description: "Initial and additional owner investments",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "3020",
    nameEn: "Retained Earnings",
    nameAr: "الأرباح المحتجزة",
    description: "Accumulated profits not distributed to owners",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "3030",
    nameEn: "Dividends / Owner Drawings",
    nameAr: "توزيعات الأرباح / سحوبات المالك",
    description: "Distributions to owners/shareholders",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // INCOME / REVENUE (4000-4099)
  // ===========================
  {
    code: "4010",
    nameEn: "Product Sales",
    nameAr: "مبيعات المنتجات",
    description: "Revenue from sale of goods",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4020",
    nameEn: "Service Revenue",
    nameAr: "إيرادات الخدمات",
    description: "Revenue from services rendered",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4030",
    nameEn: "Other Income",
    nameAr: "إيرادات أخرى",
    description: "Miscellaneous non-operating income",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4040",
    nameEn: "Interest Income",
    nameAr: "إيرادات الفوائد",
    description: "Interest earned on deposits and investments",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4050",
    nameEn: "Discounts Given",
    nameAr: "الخصومات الممنوحة",
    description: "Sales discounts and allowances (contra-revenue)",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4060",
    nameEn: "Zero-Rated Sales",
    nameAr: "مبيعات بنسبة صفر",
    description: "Exports and designated zero-rated supplies per FTA",
    type: "income",
    subType: null,
    isVatAccount: true,
    vatType: "zero_rated",
    isSystemAccount: false,
  },
  {
    code: "4070",
    nameEn: "Exempt Sales",
    nameAr: "مبيعات معفاة",
    description: "VAT-exempt supplies (financial services, residential property)",
    type: "income",
    subType: null,
    isVatAccount: true,
    vatType: "exempt",
    isSystemAccount: false,
  },

  // ===========================
  // EXPENSES (5000-5199)
  // ===========================
  {
    code: "5010",
    nameEn: "Rent Expense",
    nameAr: "مصروف الإيجار",
    description: "Office and premises rental costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5020",
    nameEn: "Salaries & Wages",
    nameAr: "الرواتب والأجور",
    description: "Employee compensation and benefits",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5030",
    nameEn: "Utilities",
    nameAr: "المرافق",
    description: "Electricity, water, and gas expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5040",
    nameEn: "Telephone & Internet",
    nameAr: "الهاتف والإنترنت",
    description: "Communication and connectivity costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5050",
    nameEn: "Office Supplies",
    nameAr: "اللوازم المكتبية",
    description: "Stationery, consumables, and small office items",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5060",
    nameEn: "Marketing & Advertising",
    nameAr: "التسويق والإعلان",
    description: "Promotional and advertising expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5070",
    nameEn: "Professional Services",
    nameAr: "الخدمات المهنية",
    description: "Legal, accounting, and consulting fees",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5080",
    nameEn: "Software Subscriptions",
    nameAr: "اشتراكات البرمجيات",
    description: "SaaS and software licensing costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5090",
    nameEn: "Travel & Meals",
    nameAr: "السفر والوجبات",
    description: "Business travel and entertainment expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5100",
    nameEn: "Depreciation Expense",
    nameAr: "مصروف الاستهلاك",
    description: "Periodic depreciation of fixed assets",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5110",
    nameEn: "Bank Charges & Fees",
    nameAr: "الرسوم والعمولات البنكية",
    description: "Bank service charges and transaction fees",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5120",
    nameEn: "Bad Debt Expense",
    nameAr: "مصروف الديون المعدومة",
    description: "Uncollectible accounts receivable written off",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
];

export function createDefaultAccountsForCompany(companyId: string): Omit<InsertAccount, "id" | "createdAt">[] {
  return defaultChartOfAccounts.map((account) => ({
    companyId,
    code: account.code,
    nameEn: account.nameEn,
    nameAr: account.nameAr,
    description: account.description,
    type: account.type,
    subType: account.subType,
    isVatAccount: account.isVatAccount,
    vatType: account.vatType,
    isSystemAccount: account.isSystemAccount,
    isActive: true,
    isArchived: false,
  }));
}
